#!/bin/bash
echo "{" > params.json
echo "	\"config\": {" >> params.json
echo "	\"specification\": {" >> params.json
echo "			\"languageCode\": \"ru-RU\"," >> params.json
echo "			\"model\": \"$2\"" >> params.json
echo "		}" >> params.json
echo "	}," >> params.json
echo "	\"audio\": {" >> params.json
echo "		\"uri\": \"https://storage.yandexcloud.net/rash2/$1\"" >> params.json
echo "	}" >> params.json
echo "}" >> params.json
